# Even Fibonacci numbers
# https://projecteuler.net/problem=2

# Problem 1
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def p002(n):
    sum = 0
    temp = 0                # store temporary curr values
    curr = 1                # first/current fibonacci terms
    next = 2                # second/next fibonacci terms
    while curr <= n:        # curr value do not exceed n
        if curr % 2 == 0:   # find even
            sum += curr     # sum even-valued terms
        temp = curr         # store curr value to temp
        curr = next         # generate next term
        next = temp + next  # adding the previous two terms
    return sum

p002(4000000) # Expected Output: 4613732